import type { Metadata } from "next";
import "./globals.css";
import Navbar from "~/components/cores/Navbar";
import Footer from "~/components/cores/Footer";
import { Toaster } from "~/components/ui/sonner";

export const metadata: Metadata = {
  title: "Depop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-worksans`}>
        <Navbar />
        <Toaster />
        {children}
        <Footer />
      </body>
    </html>
  );
}
